apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "npd-node-replace-v2.fullname" . }}-clusterrolebinding
  labels:
  {{- include "npd-node-replace-v2.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "npd-node-replace-v2.fullname" . }}-clusterrole
subjects:
- kind: ServiceAccount
  name: npd-node-replace-sa
  namespace: {{ .Release.Namespace }}
